//! Target printer: lower checked arithmetic nodes to vector API primitives.
//! No external algorithm body, kernel template or Raw-C++ statement is accepted.
use std::fmt::Write;
use super::{AscendOptions, lower::{Program,Node,Unary,Binary},plan::Allocation};
use ruda_core::kernel::Visibility;
fn line(s:&mut String,x:impl AsRef<str>){s.push_str("    ");s.push_str(x.as_ref());s.push('\n');}
fn value(p:&Program,a:&Allocation,n:usize)->String {match p.nodes[n]{Node::Input(i)=>format!("x{i}"),_=>format!("t{}",a.node_slots[n].expect("allocated temporary"))}}
fn run_begin(s:&mut String,span:u64) {
    line(s,"    for (uint32_t lane = 0; lane < count;) {");
    if span==0 {line(s,"        const uint32_t run = count - lane;");}
    else {
        line(s,format!("        const uint64_t run_left = {span}ULL - ((offset + lane) % {span}ULL);"));
        line(s,"        const uint32_t run = static_cast<uint32_t>((run_left < count - lane) ? run_left : count - lane);");
    }
    line(s,"        const uint32_t run_aligned = (run + 7U) / 8U * 8U;");
}
fn run_end(s:&mut String) {line(s,"        lane += run;");line(s,"    }");}
pub(super) fn emit(p:&Program,a:&Allocation,o:&AscendOptions,math_workspace:usize)->String{
    let mut s=String::from("// Generated by RUDA AscendCompiler from common KernelDefinition.\n// CCE is a compiler intermediate. Not direct Rust-to-ISA; no external GEMM.\n#include <stdint.h>\n#include \"kernel_operator.h\"\n\n__aicore__ inline float ruda_float_bits(uint32_t bits) {\n    union Bits { uint32_t u; float f; }; Bits b; b.u = bits; return b.f;\n}\n");
    if p.nodes.iter().any(|n|matches!(n,Node::Unary(Unary::Erf,_))) {
        s.push_str("#include \"adv_api/math/erf.h\"\nstatic constexpr AscendC::ErfConfig ruda_erf_config{AscendC::ErfAlgo::SUBSECTION_POLYNOMIAL_APPROXIMATION};\n");
    }
    if p.nodes.iter().any(|n|matches!(n,Node::Unary(Unary::Tanh,_))) {
        s.push_str("#include \"adv_api/math/tanh.h\"\nstatic constexpr AscendC::TanhConfig ruda_tanh_config{AscendC::TanhAlgo::SUBSECTION_COMPENSATION};\n");
    }
    if p.nodes.iter().any(|n|matches!(n,Node::Unary(Unary::Sin,_))) {
        s.push_str("#include \"adv_api/math/sin.h\"\nstatic constexpr AscendC::SinConfig ruda_sin_config{AscendC::SinAlgo::RADIAN_REDUCTION};\n");
    }
    if p.nodes.iter().any(|n|matches!(n,Node::Unary(Unary::Cos,_))) {
        s.push_str("#include \"adv_api/math/cos.h\"\nstatic constexpr AscendC::CosConfig ruda_cos_config{AscendC::CosAlgo::RADIAN_REDUCTION};\n");
    }
    let gather=p.load_indices.values().any(|index| **index!=super::index::Index::Lane)
        || p.nodes.iter().any(|node|matches!(node,Node::UniformInput(..)));
    let scatter=p.store_indices.values().any(|index| **index!=super::index::Index::Lane);
    if gather || scatter || !p.index_values.is_empty() || !p.predicates.is_empty() {s.push_str("template<AscendC::HardEvent event>\n__aicore__ inline void ruda_map_sync(AscendC::TPipe& pipe) {\n    const int32_t id = static_cast<int32_t>(pipe.FetchEventID(event));\n    AscendC::SetFlag<event>(id);\n    AscendC::WaitFlag<event>(id);\n}\n");}
    let args=(0..p.bindings.len()).map(|i|format!("GM_ADDR b{i}")).collect::<Vec<_>>().join(", ");
    writeln!(s,"extern \"C\" __global__ __aicore__ void {}({args}) {{",p.name).unwrap();
    line(&mut s,"KERNEL_TASK_TYPE_DEFAULT(KERNEL_TYPE_AIV_ONLY);");
    line(&mut s,format!("constexpr uint64_t elements = {}ULL;",o.elements));
    line(&mut s,format!("constexpr uint32_t tile = {}U;",o.tile_elements));
    line(&mut s,"if (elements == 0) { return; }");
    line(&mut s,"AscendC::TPipe pipe;");
    for (i,b) in p.bindings.iter().enumerate(){
        let pos=if b.visibility==Visibility::Read{"VECIN"}else{"VECOUT"};
        line(&mut s,format!("AscendC::GlobalTensor<float> g{i};"));
        line(&mut s,format!("g{i}.SetGlobalBuffer(reinterpret_cast<__gm__ float*>(b{i}), {}ULL);",b.size.map(|n|n as u64).unwrap_or(o.elements)));
        line(&mut s,format!("AscendC::TQue<AscendC::TPosition::{pos}, 1> q{i};"));
        line(&mut s,format!("pipe.InitBuffer(q{i}, 1, tile * sizeof(float));"));
        if b.visibility==Visibility::ReadWrite && p.nodes.iter().any(|n|matches!(n,Node::Input(j) if *j==i)) {
            line(&mut s,format!("AscendC::TQue<AscendC::TPosition::VECIN, 1> loadq{i};"));
            line(&mut s,format!("pipe.InitBuffer(loadq{i}, 1, tile * sizeof(float));"));
        }
    }
    if a.slots>0 {
        line(&mut s,"AscendC::TBuf<AscendC::TPosition::VECCALC> scratch;");
        line(&mut s,format!("pipe.InitBuffer(scratch, {}U * tile * sizeof(float));",a.slots));
        for i in 0..a.slots {line(&mut s,format!("auto t{i} = scratch.GetWithOffset<float>(tile, {i}U * tile * sizeof(float));"));}
    }
    if math_workspace!=0 {
        line(&mut s,"AscendC::TBuf<AscendC::TPosition::VECCALC> math_workspace;");
        line(&mut s,format!("pipe.InitBuffer(math_workspace, {math_workspace}U);"));
        line(&mut s,"auto math_tmp = math_workspace.Get<uint8_t>();");
    }
    if gather {
        line(&mut s,"AscendC::TBuf<AscendC::TPosition::VECCALC> gather_buffer;");
        line(&mut s,"pipe.InitBuffer(gather_buffer, 32U);");
        line(&mut s,"auto gather_cell = gather_buffer.Get<float>();");
        line(&mut s,"AscendC::DataCopyExtParams gather_copy{1, 4, 0, 0, 0};");
        line(&mut s,"AscendC::DataCopyPadExtParams<float> gather_pad{true, 0, 7, 0.0f};");
    }
    if scatter {
        line(&mut s,"AscendC::TBuf<AscendC::TPosition::VECCALC> scatter_buffer;");
        line(&mut s,"pipe.InitBuffer(scatter_buffer, 32U);");
        line(&mut s,"auto scatter_cell = scatter_buffer.Get<float>();");
        line(&mut s,"AscendC::DataCopyExtParams scatter_copy{1, 4, 0, 0, 0};");
    }
    line(&mut s,"const uint64_t first = static_cast<uint64_t>(AscendC::GetBlockIdx()) * tile;");
    line(&mut s,"const uint64_t step = static_cast<uint64_t>(AscendC::GetBlockNum()) * tile;");
    line(&mut s,"for (uint64_t offset = first; offset < elements; offset += step) {");
    line(&mut s,"    const uint32_t count = static_cast<uint32_t>((elements-offset < tile) ? elements-offset : tile);");
    line(&mut s,"    const uint32_t aligned = (count + 7U) / 8U * 8U;");
    line(&mut s,"    AscendC::DataCopyExtParams copy{1, count * uint32_t(sizeof(float)), 0, 0, 0};");
    line(&mut s,"    AscendC::DataCopyPadExtParams<float> pad{true, 0, static_cast<uint8_t>(aligned-count), 0.0f};");
    for (i,b) in p.bindings.iter().enumerate(){if p.nodes.iter().any(|n|matches!(n,Node::Input(j) if *j==i)) {
        let q=if b.visibility==Visibility::Read{format!("q{i}")}else{format!("loadq{i}")};
        line(&mut s,format!("    auto load{i} = {q}.AllocTensor<float>();"));
        let index=&p.load_indices[&i];
        if **index==super::index::Index::Lane {
            line(&mut s,format!("    AscendC::DataCopyPad(load{i}, g{i}[offset], copy, pad);"));
        } else if let Some(run)=index.aligned_run() {
            run_begin(&mut s,run.span);
            if run.slope==1 {
                line(&mut s,"        AscendC::DataCopyExtParams run_copy{1, run * uint32_t(sizeof(float)), 0, 0, 0};");
                line(&mut s,"        AscendC::DataCopyPadExtParams<float> run_pad{true, 0, static_cast<uint8_t>(run_aligned-run), 0.0f};");
                line(&mut s,format!("        AscendC::DataCopyPad(load{i}[lane], g{i}[{}], run_copy, run_pad);",index.cce()));
            } else {
                line(&mut s,format!("        AscendC::DataCopyPad(gather_cell, g{i}[{}], gather_copy, gather_pad);",index.cce()));
                line(&mut s,"        ruda_map_sync<AscendC::HardEvent::MTE2_S>(pipe);");
                line(&mut s,"        const float run_value = gather_cell.GetValue(0);");
                line(&mut s,"        ruda_map_sync<AscendC::HardEvent::S_MTE2>(pipe);");
                line(&mut s,format!("        AscendC::Duplicate(load{i}[lane], run_value, run_aligned);"));
            }
            run_end(&mut s);
            if run.slope==0 {
                line(&mut s,"    ruda_map_sync<AscendC::HardEvent::V_S>(pipe);");
                line(&mut s,format!("    for (uint32_t lane = count; lane < aligned; ++lane) {{ load{i}.SetValue(lane, 0.0f); }}"));
                line(&mut s,"    ruda_map_sync<AscendC::HardEvent::S_V>(pipe);");
            }
        } else {
            line(&mut s,"    ruda_map_sync<AscendC::HardEvent::V_S>(pipe);");
            line(&mut s,"    for (uint32_t lane = 0; lane < count; ++lane) {");
            line(&mut s,format!("        AscendC::DataCopyPad(gather_cell, g{i}[{}], gather_copy, gather_pad);",index.cce()));
            line(&mut s,"        ruda_map_sync<AscendC::HardEvent::MTE2_S>(pipe);");
            line(&mut s,format!("        load{i}.SetValue(lane, gather_cell.GetValue(0));"));
            line(&mut s,"        ruda_map_sync<AscendC::HardEvent::S_MTE2>(pipe);");
            line(&mut s,"    }");
            line(&mut s,format!("    for (uint32_t lane = count; lane < aligned; ++lane) {{ load{i}.SetValue(lane, 0.0f); }}"));
            line(&mut s,"    ruda_map_sync<AscendC::HardEvent::S_V>(pipe);");
        }
        line(&mut s,format!("    {q}.EnQue(load{i});"));
        line(&mut s,format!("    auto x{i} = {q}.DeQue<float>();"));
    }}
    // Operations use padded local lanes. No lane reduction can expose the padding;
    // exact-byte CopyOut writes only count live elements to GM.
    for (n,node) in p.nodes.iter().enumerate(){
        let d=value(p,a,n);
        let code=match *node {
            Node::Input(_)=>continue,
            Node::Constant(bits)=>format!("AscendC::Duplicate({d}, ruda_float_bits(0x{bits:08x}U), aligned);"),
            Node::UniformInput(binding,index)=>format!("AscendC::DataCopyPad(gather_cell, g{binding}[{index}ULL], gather_copy, gather_pad);\n    ruda_map_sync<AscendC::HardEvent::MTE2_S>(pipe);\n    const float uniform{n} = gather_cell.GetValue(0);\n    ruda_map_sync<AscendC::HardEvent::S_MTE2>(pipe);\n    AscendC::Duplicate({d}, uniform{n}, aligned);"),
            Node::IndexFloat(index)=>format!("ruda_map_sync<AscendC::HardEvent::V_S>(pipe);\n    for (uint32_t lane = 0; lane < count; ++lane) {{ {d}.SetValue(lane, static_cast<float>({})); }}\n    for (uint32_t lane = count; lane < aligned; ++lane) {{ {d}.SetValue(lane, 0.0f); }}\n    ruda_map_sync<AscendC::HardEvent::S_V>(pipe);",p.index_values[index].cce()),
            Node::IndexSelect(predicate,lhs,rhs)=>format!("ruda_map_sync<AscendC::HardEvent::V_S>(pipe);\n    for (uint32_t lane = 0; lane < count; ++lane) {{ {d}.SetValue(lane, {} ? {}.GetValue(lane) : {}.GetValue(lane)); }}\n    for (uint32_t lane = count; lane < aligned; ++lane) {{ {d}.SetValue(lane, 0.0f); }}\n    ruda_map_sync<AscendC::HardEvent::S_V>(pipe);",p.predicates[predicate].cce(),value(p,a,lhs),value(p,a,rhs)),
            Node::Unary(op,x)=>{
                let x=value(p,a,x);
                if op==Unary::Neg {format!("AscendC::Muls({d}, {x}, -1.0f, aligned);")}
                else if op==Unary::Erf {format!("AscendC::Erf<float, false, ruda_erf_config>({d}, {x}, math_tmp, aligned);")}
                else if op==Unary::Tanh {format!("AscendC::Tanh<float, false, ruda_tanh_config>({d}, {x}, math_tmp, aligned);")}
                else if op==Unary::Sin {format!("AscendC::Sin<float, false, ruda_sin_config>({d}, {x}, math_tmp, aligned);")}
                else if op==Unary::Cos {format!("AscendC::Cos<float, false, ruda_cos_config>({d}, {x}, math_tmp, aligned);")}
                else {let fun=match op{Unary::Abs=>"Abs",Unary::Exp=>"Exp",Unary::Log=>"Ln",Unary::Sqrt=>"Sqrt",Unary::Rsqrt=>"Rsqrt",Unary::Recip=>"Reciprocal",Unary::Neg|Unary::Erf|Unary::Tanh|Unary::Sin|Unary::Cos=>unreachable!()};format!("AscendC::{fun}({d}, {x}, aligned);")}
            },
            Node::Binary(op,x,y)=>{let x=value(p,a,x);let y=value(p,a,y);let fun=match op{Binary::Add=>"Add",Binary::Sub=>"Sub",Binary::Mul=>"Mul",Binary::Div=>"Div",Binary::Max=>"Max"};format!("AscendC::{fun}({d}, {x}, {y}, aligned);")},
        };
        line(&mut s,format!("    // common IR value {n}"));line(&mut s,format!("    {code}"));
        line(&mut s,"    AscendC::PipeBarrier<PIPE_V>();");
    }
    for &(i,v) in &p.stores{
        line(&mut s,format!("    auto out{i} = q{i}.AllocTensor<float>();"));
        line(&mut s,format!("    AscendC::Copy(out{i}, {}, aligned);",value(p,a,v)));
        line(&mut s,format!("    q{i}.EnQue(out{i});"));
        line(&mut s,format!("    auto ready{i} = q{i}.DeQue<float>();"));
        if *p.store_indices[&i]==super::index::Index::Lane {
            line(&mut s,format!("    AscendC::DataCopyPad(g{i}[offset], ready{i}, copy);"));
        } else if let Some(run)=p.store_indices[&i].aligned_run().filter(|run|run.slope==1) {
            run_begin(&mut s,run.span);
            line(&mut s,"        AscendC::DataCopyExtParams run_copy{1, run * uint32_t(sizeof(float)), 0, 0, 0};");
            line(&mut s,format!("        AscendC::DataCopyPad(g{i}[{}], ready{i}[lane], run_copy);",p.store_indices[&i].cce()));
            run_end(&mut s);
        } else {
            line(&mut s,"    ruda_map_sync<AscendC::HardEvent::V_S>(pipe);");
            line(&mut s,"    for (uint32_t lane = 0; lane < count; ++lane) {");
            line(&mut s,format!("        scatter_cell.SetValue(0, ready{i}.GetValue(lane));"));
            line(&mut s,"        ruda_map_sync<AscendC::HardEvent::S_MTE3>(pipe);");
            line(&mut s,format!("        AscendC::DataCopyPad(g{i}[{}], scatter_cell, scatter_copy);",p.store_indices[&i].cce()));
            line(&mut s,"        ruda_map_sync<AscendC::HardEvent::MTE3_S>(pipe);");
            line(&mut s,"    }");
        }
        line(&mut s,format!("    q{i}.FreeTensor(ready{i});"));
    }
    line(&mut s,"    AscendC::PipeBarrier<PIPE_ALL>();");
    for (i,b) in p.bindings.iter().enumerate(){if p.nodes.iter().any(|n|matches!(n,Node::Input(j) if *j==i)){
        let q=if b.visibility==Visibility::Read{format!("q{i}")}else{format!("loadq{i}")};
        line(&mut s,format!("    {q}.FreeTensor(x{i});"));}}
    line(&mut s,"}");s.push_str("}\n");s
}
