//! Lower checked 32-lane common operations to Ascend vector instructions.
//! The source of RMSNorm/Softmax formulas is row_programs.rs, not this printer.
use super::rows::{Allocation, BindingKind, Binary, Node, Program, Reduction, Unary};
use ruda_core::kernel::Visibility;
use std::fmt::Write;
fn line(s: &mut String, text: impl AsRef<str>) { s.push_str("    "); s.push_str(text.as_ref()); s.push('\n'); }
fn value(p: &Program, a: &Allocation, n: usize) -> String {
    match p.nodes[n] {
        Node::Input { binding, offset } if p.bindings[binding].kind != BindingKind::RowScalar => format!("x{binding}[{offset}U]"),
        _ => format!("t{}", a.node_slots[n].expect("checked row temporary")),
    }
}
pub(super) fn emit(p: &Program, a: &Allocation) -> String {
    let mut s = String::from("// Generated by RUDA AscendCompiler from common KernelDefinition.\n\
// Row mode: one logical 32-lane plane per row; independent of physical AIV count.\n\
// CCE is an intermediate, not handwritten operator templates or direct Rust ISA.\n\
#include <stdint.h>\n#include \"kernel_operator.h\"\n\n\
__aicore__ inline float ruda_float_bits(uint32_t bits) {\n\
    union Bits { uint32_t u; float f; }; Bits b; b.u = bits; return b.f;\n}\n\
template<AscendC::HardEvent event>\n\
__aicore__ inline void ruda_row_sync(AscendC::TPipe& pipe) {\n\
    const int32_t id = static_cast<int32_t>(pipe.FetchEventID(event));\n\
    AscendC::SetFlag<event>(id);\n    AscendC::WaitFlag<event>(id);\n}\n\n");
    let args = (0..p.bindings.len()).map(|i| format!("GM_ADDR b{i}")).collect::<Vec<_>>().join(", ");
    writeln!(s, "extern \"C\" __global__ __aicore__ void {}({args}) {{", p.name).unwrap();
    line(&mut s, "KERNEL_TASK_TYPE_DEFAULT(KERNEL_TYPE_AIV_ONLY);");
    line(&mut s, format!("constexpr uint64_t rows = {}ULL;", p.rows));
    line(&mut s, format!("constexpr uint32_t width = {}U;", p.width));
    line(&mut s, "if (rows == 0) { return; }");
    line(&mut s, "AscendC::TPipe pipe;");
    for (i, b) in p.bindings.iter().enumerate() {
        let pos = if b.arg.visibility == Visibility::Read { "VECIN" } else { "VECOUT" };
        line(&mut s, format!("AscendC::GlobalTensor<float> g{i};"));
        line(&mut s, format!("g{i}.SetGlobalBuffer(reinterpret_cast<__gm__ float*>(b{i}), {}ULL);", b.kind.count(p.rows, p.width)));
        line(&mut s, format!("AscendC::TQue<AscendC::TPosition::{pos}, 1> q{i};"));
        line(&mut s, format!("pipe.InitBuffer(q{i}, 1, {}U);", b.kind.local_count(p.width) * 4));
    }
    if a.slots != 0 {
        line(&mut s, "AscendC::TBuf<AscendC::TPosition::VECCALC> scratch;");
        line(&mut s, format!("pipe.InitBuffer(scratch, {}U);", a.slots * 128));
        for i in 0..a.slots { line(&mut s, format!("auto t{i} = scratch.GetWithOffset<float>(32, {}U);", i * 128)); }
    }
    line(&mut s, "AscendC::TBuf<AscendC::TPosition::VECCALC> reduction;");
    line(&mut s, "pipe.InitBuffer(reduction, 288U);");
    line(&mut s, "auto reduce_result = reduction.GetWithOffset<float>(8, 0);");
    line(&mut s, "auto reduce_work = reduction.GetWithOffset<float>(64, 32);");
    line(&mut s, "for (uint64_t row = AscendC::GetBlockIdx(); row < rows; row += AscendC::GetBlockNum()) {");
    for (i, b) in p.bindings.iter().enumerate() {
        if b.arg.visibility != Visibility::Read { continue; }
        let offset = match b.kind { BindingKind::Matrix => "row * width", BindingKind::SharedRow => "0", BindingKind::RowScalar => "row" };
        let count = if b.kind == BindingKind::RowScalar { 1 } else { p.width };
        let pad = if b.kind == BindingKind::RowScalar { 7 } else { 0 };
        line(&mut s, format!("    auto load{i} = q{i}.AllocTensor<float>();"));
        line(&mut s, format!("    AscendC::DataCopyExtParams copy{i}{{1, {}U, 0, 0, 0}};", count * 4));
        line(&mut s, format!("    AscendC::DataCopyPadExtParams<float> pad{i}{{true, 0, {pad}, 0.0f}};"));
        line(&mut s, format!("    AscendC::DataCopyPad(load{i}, g{i}[{offset}], copy{i}, pad{i});"));
        line(&mut s, format!("    q{i}.EnQue(load{i});"));
        line(&mut s, format!("    auto x{i} = q{i}.DeQue<float>();"));
    }
    for (n, node) in p.nodes.iter().enumerate() {
        let d = value(p, a, n);
        let code = match *node {
            Node::Input { binding, .. } => {
                if p.bindings[binding].kind != BindingKind::RowScalar { continue; }
                line(&mut s, "    ruda_row_sync<AscendC::HardEvent::MTE2_S>(pipe);");
                line(&mut s, format!("    const float scalar{n} = x{binding}.GetValue(0);"));
                line(&mut s, "    ruda_row_sync<AscendC::HardEvent::S_V>(pipe);");
                format!("AscendC::Duplicate({d}, scalar{n}, 32);")
            }
            Node::Constant(bits) => format!("AscendC::Duplicate({d}, ruda_float_bits(0x{bits:08x}U), 32);"),
            Node::Unary(op, x) => {
                let x = value(p, a, x);
                if op == Unary::Neg { format!("AscendC::Muls({d}, {x}, -1.0f, 32);") }
                else { let fun = match op { Unary::Abs => "Abs", Unary::Exp => "Exp", Unary::Log => "Ln",
                    Unary::Sqrt => "Sqrt", Unary::Rsqrt => "Rsqrt", Unary::Recip => "Reciprocal", Unary::Neg|Unary::Erf|Unary::Tanh => unreachable!() };
                    format!("AscendC::{fun}({d}, {x}, 32);") }
            }
            Node::Binary(op, x, y) => {
                let x = value(p, a, x); let y = value(p, a, y);
                let fun = match op { Binary::Add => "Add", Binary::Sub => "Sub", Binary::Mul => "Mul", Binary::Div => "Div", Binary::Max => "Max" };
                format!("AscendC::{fun}({d}, {x}, {y}, 32);")
            }
            Node::Reduce(op, x) => {
                let x = value(p, a, x);
                line(&mut s, format!("    // Common Plane reduction: exactly 32 logical values, not width={}", p.width));
                let call = match op { Reduction::Sum => format!("AscendC::ReduceSum(reduce_result, {x}, reduce_work, 32);"),
                    Reduction::Max => format!("AscendC::ReduceMax(reduce_result, {x}, reduce_work, 32, false);") };
                line(&mut s, format!("    {call}"));
                line(&mut s, "    ruda_row_sync<AscendC::HardEvent::V_S>(pipe);");
                line(&mut s, format!("    const float reduced{n} = reduce_result.GetValue(0);"));
                line(&mut s, "    ruda_row_sync<AscendC::HardEvent::S_V>(pipe);");
                format!("AscendC::Duplicate({d}, reduced{n}, 32);")
            }
        };
        line(&mut s, format!("    // common row SSA value {n}"));
        line(&mut s, format!("    {code}"));
        line(&mut s, "    AscendC::PipeBarrier<PIPE_V>();");
    }
    for (i, b) in p.bindings.iter().enumerate() {
        if b.arg.visibility != Visibility::ReadWrite { continue; }
        line(&mut s, format!("    auto out{i} = q{i}.AllocTensor<float>();"));
        for &(_, offset, v) in p.stores.iter().filter(|(binding, _, _)| *binding == i) {
            let count = if b.kind == BindingKind::RowScalar { 8 } else { 32 };
            // Copy supports VECIN->VECOUT as well as VECCALC->VECOUT on 950.
            line(&mut s, format!("    AscendC::Copy(out{i}[{offset}U], {}, {count});", value(p, a, v)));
            line(&mut s, "    AscendC::PipeBarrier<PIPE_V>();");
        }
        line(&mut s, format!("    q{i}.EnQue(out{i});"));
        line(&mut s, format!("    auto ready{i} = q{i}.DeQue<float>();"));
        let count = if b.kind == BindingKind::RowScalar { 1 } else { p.width };
        let offset = if b.kind == BindingKind::RowScalar { "row" } else { "row * width" };
        line(&mut s, format!("    AscendC::DataCopyExtParams store{i}{{1, {}U, 0, 0, 0}};", count * 4));
        line(&mut s, format!("    AscendC::DataCopyPad(g{i}[{offset}], ready{i}, store{i});"));
        line(&mut s, format!("    q{i}.FreeTensor(ready{i});"));
    }
    line(&mut s, "    AscendC::PipeBarrier<PIPE_ALL>();");
    for (i, b) in p.bindings.iter().enumerate() { if b.arg.visibility == Visibility::Read {
        line(&mut s, format!("    q{i}.FreeTensor(x{i});"));
    }}
    line(&mut s, "}"); s.push_str("}\n"); s
}
