[workspace]
members = ["rust-ascend-compiler", "rust-ascend-driver", "rust-ascend-kernels"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/shuqi2077/rust-ascend"
license = "Apache-2.0"

[workspace.dependencies]
ruda-core = { git = "https://github.com/shuqi2077/RUDA.git", rev = "c5ba9d2c0d50ab70fea54e9908b28e292e8539a6", default-features = false, features = ["ir", "compiler-std", "argument-layout"] }
rust-ascend-compiler = { path = "rust-ascend-compiler", version = "0.1.0", default-features = false }
rust-ascend-driver = { path = "rust-ascend-driver", version = "0.1.0", default-features = false }
rust-ascend-kernels = { path = "rust-ascend-kernels", version = "0.1.0" }

[package]
name = "rust-ascend"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Rust Ascend CANN runtime, common-IR compiler and device kernels"
readme = "README.md"

[dependencies]
ruda-core.workspace = true
rust-ascend-compiler = { workspace = true, features = ["ascend"] }
rust-ascend-driver = { workspace = true, features = ["runtime"] }
rust-ascend-kernels.workspace = true
ruda-tensor = { git = "https://github.com/shuqi2077/RUDA.git", rev = "c5ba9d2c0d50ab70fea54e9908b28e292e8539a6", default-features = false, features = ["api-std"] }
ruda-tensor-device = { git = "https://github.com/shuqi2077/RUDA.git", rev = "c5ba9d2c0d50ab70fea54e9908b28e292e8539a6", default-features = false, features = ["std"] }
ruda-autodiff = { git = "https://github.com/shuqi2077/RUDA.git", rev = "c5ba9d2c0d50ab70fea54e9908b28e292e8539a6", default-features = false, features = ["std"] }
ruda-kernel = { git = "https://github.com/shuqi2077/RUDA.git", rev = "c5ba9d2c0d50ab70fea54e9908b28e292e8539a6", default-features = false, features = ["frontend-std", "library"] }
ruda-optim = { git = "https://github.com/shuqi2077/RUDA.git", rev = "c5ba9d2c0d50ab70fea54e9908b28e292e8539a6", default-features = false, features = ["fused-adamw-device"] }

[dev-dependencies]
ruda-kernel = { git = "https://github.com/shuqi2077/RUDA.git", rev = "c5ba9d2c0d50ab70fea54e9908b28e292e8539a6", default-features = false, features = ["frontend-std", "library"] }
ruprim = { package = "ruPRIM", git = "https://github.com/shuqi2077/RUDA.git", rev = "c5ba9d2c0d50ab70fea54e9908b28e292e8539a6", default-features = false, features = ["std", "elementwise"] }
ruda-nn = { git = "https://github.com/shuqi2077/RUDA.git", rev = "c5ba9d2c0d50ab70fea54e9908b28e292e8539a6", default-features = false, features = ["std"] }
