//! FP32 storage updates generated by RUDA's existing native optimizer kernel.
pub use ruda_optim::{MuonConfig, Muon, MuonAdamWConfig, MuonAdamW, MuonMomentumMode,
    MuonMatrixLayout, AdjustLrFn, GradientsParams, GradientsAccumulator, Optimizer};
pub use ruda_optim::{grad_clipping, lr_scheduler};
pub use ruda_optim::{AdamW, AdamWConfig, AdamWState, Fp32MasterOptimizer, Fp32MasterState,
    SimpleOptimizer};
use crate::{compiler::AscendCompiler, driver::CannError,
    runtime::{AscendRuntime, ComputeClient, TensorBuffer,
        portable::{id::KernelId, kernel::{KernelMetadata, KernelTask, RudaKernel}, server::{KernelArguments, RudaCount}}}};
use ruda_core::{ir::{FloatKind, StorageType, Type, UIntKind,Instruction,Operator,IndexOperator}, kernel::KernelDefinition, tensor::DType};
use ruda_kernel::dsl::{InfoBuilder, prelude::{AddressType, KernelBuilder, KernelSettings, NativeExpand, RudaDim, Tensor}};
use ruda_tensor::{TensorPrimitive,api::Tensor as ApiTensor};

type Result<T> = std::result::Result<T, CannError>;
fn error(reason: impl std::fmt::Display) -> CannError {CannError::InvalidTensor(reason.to_string())}

/// Per-update scalar arguments to RUDA's FP32 `adamw_scaled` storage kernel.
/// Bias corrections are supplied explicitly, not inferred from a global counter.
#[derive(Debug, Clone, Copy)]
pub struct AdamWStorageStep {
    pub learning_rate: f32,
    pub beta1: f32,
    pub beta2: f32,
    /// Added outside the bias-corrected square root.
    pub epsilon: f32,
    pub weight_decay: f32,
    /// `1 - beta1^step` for this parameter's one-based update count.
    pub correction1: f32,
    /// `1 - beta2^step` for this parameter's one-based update count.
    pub correction2: f32,
    /// Applied in FP32 before the clipping multiplier.
    pub inverse_gradient_scale: f32,
    pub clip_multiplier: f32,
}
impl AdamWStorageStep {
    pub fn validate(&self) -> Result<()> {
        for value in [self.learning_rate,self.weight_decay] {
            if !value.is_finite() || value<0. {return Err(error("AdamW learning rate and decay must be finite and nonnegative"));}
        }
        if !(self.learning_rate*self.weight_decay).is_finite() {return Err(error("AdamW decay product overflows FP32"));}
        for beta in [self.beta1,self.beta2] {
            if !beta.is_finite() || !(0.0..1.0).contains(&beta) {return Err(error("AdamW beta must be finite in [0,1)"));}
        }
        for value in [self.epsilon,self.correction1,self.correction2,self.inverse_gradient_scale] {
            if !value.is_finite() || value<=0. {return Err(error("AdamW epsilon, corrections and inverse scale must be finite and positive"));}
        }
        if !self.clip_multiplier.is_finite() || !(0.0..=1.0).contains(&self.clip_multiplier) {
            return Err(error("AdamW clip multiplier must be finite in [0,1]"));
        }
        Ok(())
    }
    fn bits(&self) -> [u32;9] {
        [self.learning_rate,self.beta1,self.beta2,self.epsilon,self.weight_decay,
            self.correction1,self.correction2,self.inverse_gradient_scale,self.clip_multiplier].map(f32::to_bits)
    }
}

fn definition(elements: usize) -> KernelDefinition {
    let mut builder=KernelBuilder::default();
    let address=AddressType::U64;
    address.register(&mut builder.scope);
    let parameter=builder.input_tensor(Type::new(FloatKind::F32.into()));
    let gradient:NativeExpand<Tensor<f32>>=builder.input_tensor(Type::new(FloatKind::F32.into())).into();
    let first=builder.input_tensor(Type::new(FloatKind::F32.into()));
    let second=builder.input_tensor(Type::new(FloatKind::F32.into()));
    let scalars=builder.input_tensor(Type::new(FloatKind::F32.into()));
    let _=(parameter,first,second);
    let parameter:NativeExpand<Tensor<f32>>=builder.inplace_output(0).into();
    let first:NativeExpand<Tensor<f32>>=builder.inplace_output(2).into();
    let second:NativeExpand<Tensor<f32>>=builder.inplace_output(3).into();
    let [lr,beta1,beta2,epsilon,decay,correction1,correction2,inverse_scale,clip]:[NativeExpand<f32>;9]=
        std::array::from_fn(|index| {
            let value=builder.scope.create_local(Type::new(FloatKind::F32.into()));
            builder.scope.register(Instruction::new(Operator::Index(IndexOperator {list:*scalars,
                index:(index as u64).into(),vector_size:0,unroll_factor:1}),*value));
            value.into()
        });
    // The original RUDA algorithm owns all arithmetic; the fifth binding contains
    // nine dynamic FP32 scalars, not a duplicated or separate master parameter.
    ruda_optim::fused_adamw::storage::adamw_scaled::expand::<f32>(&mut builder.scope,
        parameter.clone(),gradient,parameter,first,second,
        lr,beta1,beta2,epsilon,decay,correction1,correction2,inverse_scale,clip,false);
    let kernel=builder.build(KernelSettings::default().address_type(address)
        .ruda_dim(RudaDim::new_1d(64)).kernel_name("ruda_ascend_adamw_storage"));
    let mut info=InfoBuilder::default();
    for _ in 0..4 {info.metadata.register_tensor(1,elements as u64,elements as u64,vec![elements].into(),vec![1].into(),address);}
    info.metadata.register_tensor(1,9,9,vec![9].into(),vec![1].into(),address);
    let info=info.finish(address);
    crate::compiler::arguments::specialize(kernel,&info.data,info.dynamic_metadata_offset,address.unsigned_type())
        .expect("internally constructed AdamW metadata must match RUDA's ABI")
}

struct AdamWKernel {elements: usize}
impl KernelMetadata for AdamWKernel {
    fn id(&self) -> KernelId {KernelId::new::<Self>().info(self.elements)}
    fn address_type(&self) -> StorageType {UIntKind::U64.into()}
}
impl RudaKernel for AdamWKernel {
    fn define(&self) -> KernelDefinition {definition(self.elements)}
}

fn elements(tensor: &TensorBuffer) -> Result<usize> {
    if tensor.dtype!=DType::F32 || tensor.shape.len()!=tensor.strides.len() {
        return Err(error("AdamW storage requires contiguous FP32 tensors"));
    }
    if tensor.shape.iter().any(|&dim|dim>u32::MAX as usize) {return Err(error("AdamW dimension exceeds u32"));}
    let size=tensor.shape.iter().try_fold(1usize,|n,&dim|n.checked_mul(dim))
        .ok_or_else(||error("AdamW shape overflow"))?;
    if !tensor.shape.contains(&0) {
        let mut expected=1usize;
        for (&dim,&stride) in tensor.shape.iter().zip(tensor.strides.iter()).rev() {
            if dim>1 && stride!=expected {return Err(error("AdamW storage is not contiguous"));}
            expected=expected.checked_mul(dim).ok_or_else(||error("AdamW stride overflow"))?;
        }
    }
    if size>u32::MAX as usize/4 || tensor.handle.size_in_used()<(size*4) as u64 {
        return Err(error("AdamW storage byte length is invalid"));
    }
    Ok(size)
}

/// One synchronous, in-place FP32 AdamW update through the existing RUDA kernel.
/// Parameter, gradient and moments must have equal contiguous shapes and distinct
/// storage ranges. The gradient stays unchanged; parameter and moments retain addresses.
/// Empty buffers are no-ops. No AMSGrad, implicit master cast or autograd is registered.
pub fn adamw_step(client: &ComputeClient<AscendRuntime>, parameter: &TensorBuffer,
    gradient: &TensorBuffer, first: &TensorBuffer, second: &TensorBuffer, step: AdamWStorageStep) -> Result<()> {
    step.validate()?;
    let count=elements(parameter)?;
    for tensor in [gradient,first,second] {
        if tensor.shape!=parameter.shape {return Err(error("AdamW parameter, gradient and state shapes must match"));}
        if elements(tensor)?!=count {return Err(error("AdamW tensor element count mismatch"));}
    }
    if count==0 {return client.flush().map_err(error);}
    let binding=|tensor:&TensorBuffer|tensor.handle.clone()
        .offset_end(tensor.handle.size_in_used()-count as u64*4).binding();
    let scalars=client.create_from_slice(&step.bits().into_iter().flat_map(u32::to_ne_bytes).collect::<Vec<_>>());
    client.launch(Box::new(KernelTask::<AscendCompiler,_>::new(AdamWKernel {elements:count})),
        RudaCount::Static(count.div_ceil(64) as u32,1,1),
        KernelArguments::new().with_buffer(binding(parameter)).with_buffer(binding(gradient))
            .with_buffer(binding(first)).with_buffer(binding(second)).with_buffer(scalars.clone().binding()));
    client.flush().map_err(error)
}

/// Update existing RUDA FP32 parameter/moment tensors after autodiff completes.
/// The gradient is an inner `Ascend` tensor; no optimizer graph is registered.
/// All four tensors must share a device and execution queue. Parameter and moments
/// mutate their existing storage, including external aliases, without replacement.
pub fn adamw_tensor_step<const D:usize>(parameter:&mut ApiTensor<crate::Ascend,D>,
    gradient:&ApiTensor<crate::Ascend,D>,first:&mut ApiTensor<crate::Ascend,D>,
    second:&mut ApiTensor<crate::Ascend,D>,step:AdamWStorageStep)->Result<()> {
    adamw_api_step(parameter,gradient,first,second,step)
}

pub fn adamw_ruda_tensor_step<const D:usize>(parameter:&mut ApiTensor<crate::RudaAscend,D>,
    gradient:&ApiTensor<crate::RudaAscend,D>,first:&mut ApiTensor<crate::RudaAscend,D>,
    second:&mut ApiTensor<crate::RudaAscend,D>,step:AdamWStorageStep)->Result<()> {
    adamw_api_step(parameter,gradient,first,second,step)
}

pub fn adamw_master_tensor_step<const D:usize>(parameter:&mut ApiTensor<crate::RudaAscend,D>,
    master:&mut ApiTensor<crate::RudaAscend,D>,gradient:&ApiTensor<crate::RudaAscend,D>,
    first:&mut ApiTensor<crate::RudaAscend,D>,second:&mut ApiTensor<crate::RudaAscend,D>,
    step:AdamWStorageStep)->Result<()> {
    let parameter_primitive=adamw_primitive(parameter)?;
    let master_primitive=adamw_primitive(master)?;
    let gradient_primitive=adamw_primitive(gradient)?;
    if !matches!(parameter_primitive.dtype,DType::F32|DType::F16|DType::BF16)
        || !matches!(gradient_primitive.dtype,DType::F32|DType::F16|DType::BF16)
        || master_primitive.dtype!=DType::F32 {
        return Err(error("master AdamW requires floating parameter/gradient and an explicit FP32 master"));
    }
    if parameter_primitive.meta.shape()!=master_primitive.meta.shape() {
        return Err(error("master AdamW parameter and master shapes must match"));
    }
    if parameter_primitive.device!=master_primitive.device
        || !parameter_primitive.client.same_execution_queue(&master_primitive.client) {
        return Err(error("master AdamW parameter device or execution queue mismatch"));
    }
    let storage_dtype=parameter_primitive.dtype;
    let gradient=gradient.clone().cast(DType::F32);
    adamw_api_step(master,&gradient,first,second,step)?;
    *parameter=master.clone().cast(storage_dtype);
    Ok(())
}

fn adamw_primitive<B,const D:usize>(tensor:&ApiTensor<B,D>)->Result<ruda_tensor_device::RudaTensor<AscendRuntime>>
where B:ruda_tensor::Backend<FloatTensorPrimitive=ruda_tensor_device::RudaTensor<AscendRuntime>> {
    match tensor.clone().into_primitive() {
        TensorPrimitive::Float(tensor)=>Ok(tensor),
        TensorPrimitive::QFloat(_)=>Err(error("AdamW does not dequantize parameter, gradient or state implicitly")),
    }
}

fn adamw_api_step<B,const D:usize>(parameter:&mut ApiTensor<B,D>,gradient:&ApiTensor<B,D>,
    first:&mut ApiTensor<B,D>,second:&mut ApiTensor<B,D>,step:AdamWStorageStep)->Result<()>
where B:ruda_tensor::Backend<FloatTensorPrimitive=ruda_tensor_device::RudaTensor<AscendRuntime>> {
    let p=adamw_primitive(parameter)?;let g=adamw_primitive(gradient)?;
    let m=adamw_primitive(first)?;let v=adamw_primitive(second)?;
    for other in [&g,&m,&v] {
        if p.device!=other.device || !p.client.same_execution_queue(&other.client) {
            return Err(error("AdamW tensor device or execution queue mismatch"));
        }
    }
    let buffer=|tensor:ruda_tensor_device::RudaTensor<AscendRuntime>|TensorBuffer {
        handle:tensor.handle,shape:tensor.meta.shape().clone(),strides:tensor.meta.strides().clone(),dtype:tensor.dtype,
    };
    let client=p.client.clone();
    adamw_step(&client,&buffer(p),&buffer(g),&buffer(m),&buffer(v),step)
}

#[cfg(test)]
mod tests {
    use super::*;
    use ruda_core::{compiler::Compiler, launch::ExecutionMode};
    use crate::compiler::{AscendOptions, AscendTarget};
    fn step() -> AdamWStorageStep {AdamWStorageStep {learning_rate:0.01,beta1:0.9,beta2:0.999,
        epsilon:1e-5,weight_decay:0.01,correction1:0.1,correction2:0.001,
        inverse_gradient_scale:0.125,clip_multiplier:0.75}}
    #[test]
    fn actual_ruda_adamw_storage_ir_compiles_without_duplicate_master_binding() {
        for n in [0,1,65,1025] {
            let kernel=AscendCompiler.compile(definition(n),&AscendOptions {target:Some(AscendTarget::Ascend950DT),
                elements:n as u64,..Default::default()},ExecutionMode::Checked,UIntKind::U64.into()).unwrap();
            assert_eq!(kernel.bindings().len(),5);
            assert_eq!(kernel.bindings().iter().map(|b|b.writable).collect::<Vec<_>>(),[true,false,true,true,false]);
            assert!(kernel.bindings()[..4].iter().all(|b|b.bytes==n as u64*4));
            assert_eq!(kernel.bindings()[4].bytes,36);
            assert!(kernel.requires_initialized_outputs());
            assert!(kernel.source().contains("AscendC::Sqrt"));
            for index in 0..9 {assert!(kernel.source().contains(&format!("g4[{index}ULL]")));}
        }
    }
    #[test]
    fn storage_scalar_contract_rejects_invalid_values() {
        step().validate().unwrap();
        for value in [0.,-1.,f32::NAN,f32::INFINITY] {
            assert!(AdamWStorageStep {correction1:value,..step()}.validate().is_err());
        }
        assert!(AdamWStorageStep {clip_multiplier:1.1,..step()}.validate().is_err());
        assert!(AdamWStorageStep {beta2:1.,..step()}.validate().is_err());
    }
}
