//! FP32 storage updates generated by RUDA's existing native optimizer kernel.
use crate::{compiler::AscendCompiler, driver::CannError,
    runtime::{AscendRuntime, ComputeClient, TensorBuffer,
        portable::{id::KernelId, kernel::{KernelMetadata, KernelTask, RudaKernel}, server::{KernelArguments, RudaCount}}}};
use ruda_core::{ir::{FloatKind, StorageType, Type, UIntKind}, kernel::KernelDefinition, tensor::DType};
use ruda_kernel::dsl::{InfoBuilder, prelude::{AddressType, KernelBuilder, KernelSettings, NativeExpand, RudaDim, Tensor}};

type Result<T> = std::result::Result<T, CannError>;
fn error(reason: impl std::fmt::Display) -> CannError {CannError::InvalidTensor(reason.to_string())}

/// Per-update scalar arguments to RUDA's FP32 `adamw_scaled` storage kernel.
/// Bias corrections are supplied explicitly, not inferred from a global counter.
#[derive(Debug, Clone, Copy)]
pub struct AdamWStorageStep {
    pub learning_rate: f32,
    pub beta1: f32,
    pub beta2: f32,
    /// Added outside the bias-corrected square root.
    pub epsilon: f32,
    pub weight_decay: f32,
    /// `1 - beta1^step` for this parameter's one-based update count.
    pub correction1: f32,
    /// `1 - beta2^step` for this parameter's one-based update count.
    pub correction2: f32,
    /// Applied in FP32 before the clipping multiplier.
    pub inverse_gradient_scale: f32,
    pub clip_multiplier: f32,
}
impl AdamWStorageStep {
    pub fn validate(&self) -> Result<()> {
        for value in [self.learning_rate,self.weight_decay] {
            if !value.is_finite() || value<0. {return Err(error("AdamW learning rate and decay must be finite and nonnegative"));}
        }
        if !(self.learning_rate*self.weight_decay).is_finite() {return Err(error("AdamW decay product overflows FP32"));}
        for beta in [self.beta1,self.beta2] {
            if !beta.is_finite() || !(0.0..1.0).contains(&beta) {return Err(error("AdamW beta must be finite in [0,1)"));}
        }
        for value in [self.epsilon,self.correction1,self.correction2,self.inverse_gradient_scale] {
            if !value.is_finite() || value<=0. {return Err(error("AdamW epsilon, corrections and inverse scale must be finite and positive"));}
        }
        if !self.clip_multiplier.is_finite() || !(0.0..=1.0).contains(&self.clip_multiplier) {
            return Err(error("AdamW clip multiplier must be finite in [0,1]"));
        }
        Ok(())
    }
    fn bits(&self) -> [u32;9] {
        [self.learning_rate,self.beta1,self.beta2,self.epsilon,self.weight_decay,
            self.correction1,self.correction2,self.inverse_gradient_scale,self.clip_multiplier].map(f32::to_bits)
    }
}

fn definition(elements: usize, step: AdamWStorageStep) -> KernelDefinition {
    let mut builder=KernelBuilder::default();
    let address=AddressType::U64;
    address.register(&mut builder.scope);
    let parameter=builder.input_tensor(Type::new(FloatKind::F32.into()));
    let gradient:NativeExpand<Tensor<f32>>=builder.input_tensor(Type::new(FloatKind::F32.into())).into();
    let first=builder.input_tensor(Type::new(FloatKind::F32.into()));
    let second=builder.input_tensor(Type::new(FloatKind::F32.into()));
    let _=(parameter,first,second);
    let parameter:NativeExpand<Tensor<f32>>=builder.inplace_output(0).into();
    let first:NativeExpand<Tensor<f32>>=builder.inplace_output(2).into();
    let second:NativeExpand<Tensor<f32>>=builder.inplace_output(3).into();
    // The original RUDA algorithm owns all arithmetic. With separate_master=false,
    // master is compile-time unused, so no fifth/unused binding is introduced.
    ruda_optim::fused_adamw::storage::adamw_scaled::expand::<f32>(&mut builder.scope,
        parameter.clone(),gradient,parameter,first,second,
        step.learning_rate.into(),step.beta1.into(),step.beta2.into(),step.epsilon.into(),step.weight_decay.into(),
        step.correction1.into(),step.correction2.into(),step.inverse_gradient_scale.into(),step.clip_multiplier.into(),false);
    let kernel=builder.build(KernelSettings::default().address_type(address)
        .ruda_dim(RudaDim::new_1d(64)).kernel_name("ruda_ascend_adamw_storage"));
    let mut info=InfoBuilder::default();
    for _ in 0..4 {info.metadata.register_tensor(1,elements,elements,vec![elements].into(),vec![1].into(),address);}
    let info=info.finish(address);
    crate::compiler::arguments::specialize(kernel,&info.data,info.dynamic_metadata_offset,address.unsigned_type())
        .expect("internally constructed AdamW metadata must match RUDA's ABI")
}

struct AdamWKernel {elements: usize, step: AdamWStorageStep}
impl KernelMetadata for AdamWKernel {
    fn id(&self) -> KernelId {KernelId::new::<Self>().info((self.elements,self.step.bits()))}
    fn address_type(&self) -> StorageType {UIntKind::U64.into()}
}
impl RudaKernel for AdamWKernel {
    fn define(&self) -> KernelDefinition {definition(self.elements,self.step)}
}

fn elements(tensor: &TensorBuffer) -> Result<usize> {
    if tensor.dtype!=DType::F32 || tensor.shape.len()!=tensor.strides.len() {
        return Err(error("AdamW storage requires contiguous FP32 tensors"));
    }
    if tensor.shape.iter().any(|&dim|dim>u32::MAX as usize) {return Err(error("AdamW dimension exceeds u32"));}
    let size=tensor.shape.iter().try_fold(1usize,|n,&dim|n.checked_mul(dim))
        .ok_or_else(||error("AdamW shape overflow"))?;
    if !tensor.shape.contains(&0) {
        let mut expected=1usize;
        for (&dim,&stride) in tensor.shape.iter().zip(&tensor.strides).rev() {
            if dim>1 && stride!=expected {return Err(error("AdamW storage is not contiguous"));}
            expected=expected.checked_mul(dim).ok_or_else(||error("AdamW stride overflow"))?;
        }
    }
    if size>u32::MAX as usize/4 || tensor.handle.size_in_used()<(size*4) as u64 {
        return Err(error("AdamW storage byte length is invalid"));
    }
    Ok(size)
}

/// One synchronous, in-place FP32 AdamW update through the existing RUDA kernel.
/// Parameter, gradient and moments must have equal contiguous shapes and distinct
/// storage ranges. The gradient stays unchanged; parameter and moments retain addresses.
/// Empty buffers are no-ops. No AMSGrad, implicit master cast or autograd is registered.
pub fn adamw_step(client: &ComputeClient<AscendRuntime>, parameter: &TensorBuffer,
    gradient: &TensorBuffer, first: &TensorBuffer, second: &TensorBuffer, step: AdamWStorageStep) -> Result<()> {
    step.validate()?;
    let count=elements(parameter)?;
    for tensor in [gradient,first,second] {
        if tensor.shape!=parameter.shape {return Err(error("AdamW parameter, gradient and state shapes must match"));}
        if elements(tensor)?!=count {return Err(error("AdamW tensor element count mismatch"));}
    }
    if count==0 {return client.flush().map_err(error);}
    let binding=|tensor:&TensorBuffer|tensor.handle.clone()
        .offset_end(tensor.handle.size_in_used()-count as u64*4).binding();
    client.launch(Box::new(KernelTask::<AscendCompiler,_>::new(AdamWKernel {elements:count,step})),
        RudaCount::Static(count.div_ceil(64) as u32,1,1),
        KernelArguments::new().with_buffer(binding(parameter)).with_buffer(binding(gradient))
            .with_buffer(binding(first)).with_buffer(binding(second)));
    client.flush().map_err(error)
}

#[cfg(test)]
mod tests {
    use super::*;
    use ruda_core::{compiler::Compiler, launch::ExecutionMode};
    use crate::compiler::{AscendOptions, AscendTarget};
    fn step() -> AdamWStorageStep {AdamWStorageStep {learning_rate:0.01,beta1:0.9,beta2:0.999,
        epsilon:1e-5,weight_decay:0.01,correction1:0.1,correction2:0.001,
        inverse_gradient_scale:0.125,clip_multiplier:0.75}}
    #[test]
    fn actual_ruda_adamw_storage_ir_compiles_without_duplicate_master_binding() {
        for n in [0,1,65,1025] {
            let kernel=AscendCompiler.compile(definition(n,step()),&AscendOptions {target:Some(AscendTarget::Ascend950DT),
                elements:n as u64,..Default::default()},ExecutionMode::Checked,UIntKind::U64.into()).unwrap();
            assert_eq!(kernel.bindings().len(),4);
            assert_eq!(kernel.bindings().iter().map(|b|b.writable).collect::<Vec<_>>(),[true,false,true,true]);
            assert!(kernel.bindings().iter().all(|b|b.bytes==n as u64*4));
            assert!(kernel.requires_initialized_outputs());
            assert!(kernel.source().contains("AscendC::Sqrt"));
        }
    }
    #[test]
    fn storage_scalar_contract_rejects_invalid_values() {
        step().validate().unwrap();
        for value in [0.,-1.,f32::NAN,f32::INFINITY] {
            assert!(AdamWStorageStep {correction1:value,..step()}.validate().is_err());
        }
        assert!(AdamWStorageStep {clip_multiplier:1.1,..step()}.validate().is_err());
        assert!(AdamWStorageStep {beta2:1.,..step()}.validate().is_err());
    }
}
