[package]
name = "rust-ascend-compiler"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Common Rust kernel IR to Ascend CCE compiler"

[features]
default = ["ascend"]
ascend = []
ptx = ["dep:upstream-compiler"]

[dependencies]
ruda-core.workspace = true
upstream-compiler = { package = "ruda-compiler", git = "https://github.com/shuqi2077/RUDA.git", rev = "c5ba9d2c0d50ab70fea54e9908b28e292e8539a6", default-features = false, features = ["ptx"], optional = true }

[[example]]
name = "ascend_ir"
path = "examples/ascend_ir.rs"
required-features = ["ascend"]
